name: CI
on:
 push:
   branches: [ "*" ]
jobs:
 build-and-deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4

   - name: Calculate port for branch
     id: port
     run: |
       BRANCH_NAME="${{ github.ref_name }}"
       if [ "$BRANCH_NAME" = "main" ]; then
         PORT=4321
       else
         # Generate unique port for branch (4322-4999)
         HASH=$(echo -n "$BRANCH_NAME" | md5sum | cut -c1-8)
         PORT=$((4322 + 0x$HASH % 678))
       fi
       echo "port=$PORT" >> $GITHUB_OUTPUT
       echo "Using port $PORT for branch $BRANCH_NAME"

   - name: docker login
     uses: docker/login-action@v3
     with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}

   - name: docker build and push
     uses: docker/build-push-action@v5
     with:
       context: .
       push: true
       tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}
       build-args: |
         PORT=${{ steps.port.outputs.port }}
       secrets: |
         datocms_token=${{ secrets.DATOCMS_TOKEN }}

   - name: create or update container on Magic Containers
     uses: ./.github/actions/bunny
     with:
       app_id: ${{ secrets.APP_ID }}
       api_key: ${{ secrets.BUNNYNET_API_KEY }}
       container_name: ${{ github.ref_name }}
       image_tag: "${{ github.ref_name }}-${{ github.sha }}"
       port: ${{ steps.port.outputs.port }}
       environment_variables: |
         DATOCMS_TOKEN=${{ secrets.DATOCMS_TOKEN }}
