name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: docker login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: docker build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}
        secrets: |
          datocms_token=${{ secrets.DATOCMS_TOKEN }}

    - name: Check if container exists in Bunny
      id: check_container
      env:
        API_KEY: ${{ secrets.BUNNYNET_API_KEY }}
        APP_ID: ${{ secrets.APP_ID }}
        CONTAINER_NAME: ${{ github.ref_name }}
      run: |
        set -e

        # Get token
        TOKEN=$(curl -s -X POST https://api.bunny.net/apikey/exchange \
          -H "Content-Type: application/json" \
          -H "AccessKey: $API_KEY" \
          -d "{\"AccessKey\":\"$API_KEY\"}" | jq -r '.Token')

        if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
          echo "Failed to retrieve token"
          exit 1
        fi

        # Get app configuration
        CONFIG=$(curl -s -H "Authorization: $TOKEN" \
          "https://api-mc.opsbunny.net/v1/namespaces/default/applications/$APP_ID/configuration")

        # Check if container name exists
        EXISTS=$(echo "$CONFIG" | jq -r \
          --arg name "$CONTAINER_NAME" \
          '.containerTemplates[]?.name == $name' | grep -c true)

        if [ "$EXISTS" -gt 0 ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: update container image on Magic Containers
      if: steps.check_container.outputs.exists == 'true'
      uses: BunnyWay/actions/container-update-image@main
      with:
        app_id: ${{ secrets.APP_ID }}
        api_key: ${{ secrets.BUNNYNET_API_KEY }}
        container: ${{ github.ref_name }}
        image_tag: "${{ github.ref_name }}-${{ github.sha }}"
